-- Crown Lizard Build 92: owner-only campaign codes and server-owned crate credits.
-- Safe to run repeatedly in the Supabase SQL editor.
begin;

alter table public.player_wallets
  add column if not exists free_crate_credits integer not null default 0
  check (free_crate_credits between 0 and 1000000);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'owner' check (role = 'owner'),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.promo_codes (
  id uuid primary key default gen_random_uuid(),
  code_hash text not null unique check (code_hash ~ '^[a-f0-9]{64}$'),
  code_hint text not null check (code_hint ~ '^CROWN-\*{4}-\*{4}-[A-HJ-NP-Z2-9]{4}$'),
  campaign_name text not null check (char_length(campaign_name) between 3 and 48),
  reward_type text not null check (reward_type in ('shards', 'crate_credit')),
  reward_amount integer not null,
  starts_at timestamptz not null,
  expires_at timestamptz not null,
  max_redemptions integer not null check (max_redemptions between 1 and 100000),
  per_player_limit integer not null default 1 check (per_player_limit = 1),
  redeemed_count integer not null default 0 check (redeemed_count >= 0 and redeemed_count <= max_redemptions),
  status text not null default 'active' check (status in ('active', 'paused', 'revoked', 'exhausted')),
  note text not null default '' check (char_length(note) <= 160),
  created_by uuid not null references public.admin_users(user_id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (expires_at > starts_at),
  check (
    (reward_type = 'shards' and reward_amount between 25 and 2500)
    or (reward_type = 'crate_credit' and reward_amount between 1 and 5)
  )
);

create table if not exists public.promo_redemptions (
  id uuid primary key default gen_random_uuid(),
  code_id uuid not null references public.promo_codes(id) on delete restrict,
  user_id uuid not null references auth.users(id) on delete cascade,
  reward_type text not null check (reward_type in ('shards', 'crate_credit')),
  reward_amount integer not null check (reward_amount > 0),
  balance_after integer not null check (balance_after between 0 and 1000000000),
  free_crate_credits_after integer not null check (free_crate_credits_after between 0 and 1000000),
  redeemed_at timestamptz not null default now(),
  unique (code_id, user_id)
);

create table if not exists public.promo_redemption_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  ip_hash text not null check (ip_hash ~ '^[a-f0-9]{64}$'),
  successful boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references public.admin_users(user_id) on delete restrict,
  action text not null check (action in ('promo.create', 'promo.pause', 'promo.activate', 'promo.revoke')),
  target_id uuid references public.promo_codes(id) on delete restrict,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists promo_codes_status_idx on public.promo_codes (status, expires_at);
create index if not exists promo_redemptions_user_idx on public.promo_redemptions (user_id, redeemed_at desc);
create index if not exists promo_attempts_user_idx on public.promo_redemption_attempts (user_id, created_at desc);
create index if not exists promo_attempts_ip_idx on public.promo_redemption_attempts (ip_hash, created_at desc);
create index if not exists admin_audit_log_created_idx on public.admin_audit_log (created_at desc);

alter table public.admin_users enable row level security;
alter table public.promo_codes enable row level security;
alter table public.promo_redemptions enable row level security;
alter table public.promo_redemption_attempts enable row level security;
alter table public.admin_audit_log enable row level security;

revoke all on table public.admin_users from public, anon, authenticated;
revoke all on table public.promo_codes from public, anon, authenticated;
revoke all on table public.promo_redemptions from public, anon, authenticated;
revoke all on table public.promo_redemption_attempts from public, anon, authenticated;
revoke all on table public.admin_audit_log from public, anon, authenticated;

create or replace function public.is_crown_admin(p_user_id uuid)
returns boolean
language sql
security definer
stable
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_users admin
     where admin.user_id = p_user_id and admin.active and admin.role = 'owner'
  );
$$;

revoke all on function public.is_crown_admin(uuid) from public, anon, authenticated;
grant execute on function public.is_crown_admin(uuid) to service_role;

create or replace function public.create_reward_code(
  p_admin_user_id uuid,
  p_code_hash text,
  p_code_hint text,
  p_campaign_name text,
  p_reward_type text,
  p_reward_amount integer,
  p_starts_at timestamptz,
  p_expires_at timestamptz,
  p_max_redemptions integer,
  p_note text
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  created public.promo_codes%rowtype;
begin
  if not public.is_crown_admin(p_admin_user_id) then return jsonb_build_object('error', 'ADMIN_REQUIRED'); end if;
  if p_code_hash !~ '^[a-f0-9]{64}$'
     or p_code_hint !~ '^CROWN-\*{4}-\*{4}-[A-HJ-NP-Z2-9]{4}$'
     or char_length(btrim(coalesce(p_campaign_name, ''))) not between 3 and 48
     or char_length(coalesce(p_note, '')) > 160
     or p_starts_at < now() - interval '5 minutes'
     or p_expires_at <= p_starts_at
     or p_expires_at > p_starts_at + interval '90 days'
     or p_max_redemptions not between 1 and 100000
     or not (
       (p_reward_type = 'shards' and p_reward_amount between 25 and 2500)
       or (p_reward_type = 'crate_credit' and p_reward_amount between 1 and 5)
     ) then
    return jsonb_build_object('error', 'INVALID_PROMO');
  end if;

  insert into public.promo_codes (
    code_hash, code_hint, campaign_name, reward_type, reward_amount,
    starts_at, expires_at, max_redemptions, note, created_by
  ) values (
    p_code_hash, p_code_hint, upper(btrim(p_campaign_name)), p_reward_type, p_reward_amount,
    p_starts_at, p_expires_at, p_max_redemptions, btrim(coalesce(p_note, '')), p_admin_user_id
  ) returning * into created;

  insert into public.admin_audit_log (admin_user_id, action, target_id, metadata)
  values (
    p_admin_user_id, 'promo.create', created.id,
    jsonb_build_object('rewardType', created.reward_type, 'rewardAmount', created.reward_amount, 'maxRedemptions', created.max_redemptions)
  );

  return jsonb_build_object(
    'id', created.id, 'codeHint', created.code_hint, 'campaignName', created.campaign_name,
    'rewardType', created.reward_type, 'rewardAmount', created.reward_amount,
    'startsAt', created.starts_at, 'expiresAt', created.expires_at,
    'maxRedemptions', created.max_redemptions, 'redeemedCount', 0, 'status', created.status,
    'createdAt', created.created_at
  );
exception when unique_violation then
  return jsonb_build_object('error', 'CODE_COLLISION');
end;
$$;

revoke all on function public.create_reward_code(uuid, text, text, text, text, integer, timestamptz, timestamptz, integer, text) from public, anon, authenticated;
grant execute on function public.create_reward_code(uuid, text, text, text, text, integer, timestamptz, timestamptz, integer, text) to service_role;

create or replace function public.set_reward_code_status(
  p_admin_user_id uuid,
  p_code_id uuid,
  p_status text
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  promo public.promo_codes%rowtype;
begin
  if not public.is_crown_admin(p_admin_user_id) then return jsonb_build_object('error', 'ADMIN_REQUIRED'); end if;
  if p_status not in ('active', 'paused', 'revoked') then return jsonb_build_object('error', 'INVALID_STATUS'); end if;

  select * into promo from public.promo_codes where id = p_code_id for update;
  if not found then return jsonb_build_object('error', 'PROMO_NOT_FOUND'); end if;
  if promo.status in ('revoked', 'exhausted') then return jsonb_build_object('error', 'PROMO_FINAL'); end if;

  update public.promo_codes set status = p_status, updated_at = now() where id = p_code_id returning * into promo;
  insert into public.admin_audit_log (admin_user_id, action, target_id, metadata)
  values (p_admin_user_id, 'promo.' || case when p_status = 'active' then 'activate' else p_status end, p_code_id, '{}'::jsonb);

  return jsonb_build_object('id', promo.id, 'status', promo.status, 'updatedAt', promo.updated_at);
end;
$$;

revoke all on function public.set_reward_code_status(uuid, uuid, text) from public, anon, authenticated;
grant execute on function public.set_reward_code_status(uuid, uuid, text) to service_role;

create or replace function public.redeem_reward_code(
  p_user_id uuid,
  p_code_hash text,
  p_ip_hash text
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  promo public.promo_codes%rowtype;
  wallet public.player_wallets%rowtype;
  attempt_id bigint;
  recent_attempts integer;
begin
  if p_user_id is null or p_code_hash !~ '^[a-f0-9]{64}$' or p_ip_hash !~ '^[a-f0-9]{64}$' then
    return jsonb_build_object('error', 'INVALID_CODE');
  end if;
  if not exists (select 1 from auth.users where id = p_user_id and not is_anonymous) then
    return jsonb_build_object('error', 'ACCOUNT_REQUIRED');
  end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_user_id::text || ':' || p_ip_hash, 0));
  select count(*) into recent_attempts
    from public.promo_redemption_attempts
   where (user_id = p_user_id or ip_hash = p_ip_hash)
     and created_at >= now() - interval '10 minutes';
  if recent_attempts >= 8 then return jsonb_build_object('error', 'RATE_LIMITED'); end if;

  insert into public.promo_redemption_attempts (user_id, ip_hash)
  values (p_user_id, p_ip_hash) returning id into attempt_id;

  select * into promo from public.promo_codes where code_hash = p_code_hash for update;
  if not found
     or promo.status <> 'active'
     or promo.starts_at > now()
     or promo.expires_at <= now()
     or promo.redeemed_count >= promo.max_redemptions then
    return jsonb_build_object('error', 'INVALID_CODE');
  end if;

  if exists (select 1 from public.promo_redemptions where code_id = promo.id and user_id = p_user_id) then
    return jsonb_build_object('error', 'ALREADY_REDEEMED');
  end if;

  insert into public.player_wallets (user_id) values (p_user_id) on conflict (user_id) do nothing;
  select * into wallet from public.player_wallets where user_id = p_user_id for update;

  if promo.reward_type = 'shards' then
    update public.player_wallets
       set balance = balance + promo.reward_amount, updated_at = now()
     where user_id = p_user_id returning * into wallet;
  else
    update public.player_wallets
       set free_crate_credits = free_crate_credits + promo.reward_amount, updated_at = now()
     where user_id = p_user_id returning * into wallet;
  end if;

  insert into public.promo_redemptions (
    code_id, user_id, reward_type, reward_amount, balance_after, free_crate_credits_after
  ) values (
    promo.id, p_user_id, promo.reward_type, promo.reward_amount, wallet.balance, wallet.free_crate_credits
  );

  update public.promo_codes
     set redeemed_count = redeemed_count + 1,
         status = case when redeemed_count + 1 >= max_redemptions then 'exhausted' else status end,
         updated_at = now()
   where id = promo.id;

  insert into public.economy_transactions (user_id, external_id, kind, amount, balance_after, metadata)
  values (
    p_user_id, 'promo:' || promo.id::text,
    case when promo.reward_type = 'shards' then 'promo_shards' else 'promo_crate_credit' end,
    case when promo.reward_type = 'shards' then promo.reward_amount else 0 end,
    wallet.balance,
    jsonb_build_object('codeId', promo.id, 'campaignName', promo.campaign_name, 'rewardType', promo.reward_type, 'rewardAmount', promo.reward_amount, 'freeCrateCreditsAfter', wallet.free_crate_credits)
  );

  update public.promo_redemption_attempts set successful = true where id = attempt_id;
  return jsonb_build_object(
    'redeemed', true, 'campaignName', promo.campaign_name,
    'rewardType', promo.reward_type, 'rewardAmount', promo.reward_amount,
    'balance', wallet.balance, 'freeCrateCredits', wallet.free_crate_credits
  );
end;
$$;

revoke all on function public.redeem_reward_code(uuid, text, text) from public, anon, authenticated;
grant execute on function public.redeem_reward_code(uuid, text, text) to service_role;

-- Free credits enter the existing crate transaction. Odds, pity, inventory and
-- duplicate salvage stay identical; only the 150-shard charge is skipped.
create or replace function public.open_crown_crate(
  p_user_id uuid,
  p_opening_id uuid,
  p_tier_roll integer,
  p_cosmetic_roll integer
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  wallet public.player_wallets%rowtype;
  existing_tx public.economy_transactions%rowtype;
  selected_tier text;
  selected_cosmetic text;
  guaranteed boolean;
  is_duplicate boolean;
  uses_free_credit boolean;
  salvage integer;
  candidate_count integer;
  opening_number integer;
  resulting_balance integer;
  outcome jsonb;
begin
  if p_tier_roll < 0 or p_tier_roll > 9999 then raise exception 'invalid tier roll'; end if;
  if p_cosmetic_roll < 0 or p_cosmetic_roll > 999999 then raise exception 'invalid cosmetic roll'; end if;
  insert into public.player_wallets (user_id) values (p_user_id) on conflict (user_id) do nothing;
  select * into wallet from public.player_wallets where user_id = p_user_id for update;
  select * into existing_tx from public.economy_transactions
   where user_id = p_user_id and external_id = 'crate:' || p_opening_id::text;
  if found then
    return jsonb_build_object('duplicateRequest', true, 'balance', existing_tx.balance_after, 'outcome', existing_tx.metadata->'outcome');
  end if;

  uses_free_credit := wallet.free_crate_credits > 0;
  if not uses_free_credit and wallet.balance < 150 then
    return jsonb_build_object('error', 'NOT_ENOUGH_SHARDS', 'balance', wallet.balance, 'freeCrateCredits', wallet.free_crate_credits);
  end if;

  guaranteed := wallet.since_sovereign >= 199;
  selected_tier := case
    when guaranteed then 'sovereign'
    when p_tier_roll < 5800 then 'uncommon'
    when p_tier_roll < 8600 then 'rare'
    when p_tier_roll < 9600 then 'royal'
    when p_tier_roll < 9950 then 'mythic'
    else 'sovereign'
  end;
  select count(*) into candidate_count from public.cosmetic_catalog
   where rarity = selected_tier and active and acquisition_source = 'crate';
  if candidate_count = 0 then raise exception 'empty cosmetic tier'; end if;
  select id into selected_cosmetic from public.cosmetic_catalog
   where rarity = selected_tier and active and acquisition_source = 'crate'
   order by sort_order offset (p_cosmetic_roll % candidate_count) limit 1;

  if wallet.opens = 0 and exists (
    select 1 from public.player_inventory where user_id = p_user_id and cosmetic_id = selected_cosmetic
  ) then
    select count(*) into candidate_count from public.cosmetic_catalog catalog
     where catalog.rarity = selected_tier and catalog.active and catalog.acquisition_source = 'crate'
       and not exists (select 1 from public.player_inventory owned where owned.user_id = p_user_id and owned.cosmetic_id = catalog.id);
    if candidate_count > 0 then
      select catalog.id into selected_cosmetic from public.cosmetic_catalog catalog
       where catalog.rarity = selected_tier and catalog.active and catalog.acquisition_source = 'crate'
         and not exists (select 1 from public.player_inventory owned where owned.user_id = p_user_id and owned.cosmetic_id = catalog.id)
       order by catalog.sort_order offset (p_cosmetic_roll % candidate_count) limit 1;
    else
      select count(*) into candidate_count from public.cosmetic_catalog catalog
       where catalog.active and catalog.acquisition_source = 'crate'
         and not exists (select 1 from public.player_inventory owned where owned.user_id = p_user_id and owned.cosmetic_id = catalog.id);
      if candidate_count > 0 then
        select catalog.id into selected_cosmetic from public.cosmetic_catalog catalog
         where catalog.active and catalog.acquisition_source = 'crate'
           and not exists (select 1 from public.player_inventory owned where owned.user_id = p_user_id and owned.cosmetic_id = catalog.id)
         order by catalog.sort_order offset (p_cosmetic_roll % candidate_count) limit 1;
        select rarity into selected_tier from public.cosmetic_catalog where id = selected_cosmetic;
      end if;
    end if;
  end if;

  select exists (select 1 from public.player_inventory where user_id = p_user_id and cosmetic_id = selected_cosmetic) into is_duplicate;
  salvage := case selected_tier when 'uncommon' then 15 when 'rare' then 35 when 'royal' then 75 when 'mythic' then 150 when 'sovereign' then 300 else 0 end;
  if not is_duplicate then salvage := 0; end if;
  opening_number := wallet.opens + 1;
  resulting_balance := wallet.balance - case when uses_free_credit then 0 else 150 end + salvage;

  if not is_duplicate then
    insert into public.player_inventory (user_id, cosmetic_id, source)
    values (p_user_id, selected_cosmetic, 'crate') on conflict (user_id, cosmetic_id) do nothing;
  end if;

  update public.player_wallets
     set balance = resulting_balance,
         free_crate_credits = free_crate_credits - case when uses_free_credit then 1 else 0 end,
         opens = opening_number,
         since_sovereign = case when selected_tier = 'sovereign' then 0 else least(199, wallet.since_sovereign + 1) end,
         updated_at = now()
   where user_id = p_user_id;

  outcome := jsonb_build_object(
    'openingId', p_opening_id, 'openingNumber', opening_number,
    'cosmeticId', selected_cosmetic, 'tier', selected_tier,
    'duplicate', is_duplicate, 'salvageValue', salvage,
    'guaranteedSovereign', guaranteed, 'freeCredit', uses_free_credit,
    'source', 'crate', 'createdAt', now()
  );
  insert into public.economy_transactions (user_id, external_id, kind, amount, balance_after, opening_id, metadata)
  values (
    p_user_id, 'crate:' || p_opening_id::text,
    case when uses_free_credit then 'crate_open_free' else 'crate_open' end,
    -(case when uses_free_credit then 0 else 150 end) + salvage,
    resulting_balance, p_opening_id,
    jsonb_build_object('cost', case when uses_free_credit then 0 else 150 end, 'salvage', salvage, 'freeCredit', uses_free_credit, 'outcome', outcome)
  );
  return jsonb_build_object(
    'duplicateRequest', false, 'balance', resulting_balance,
    'freeCrateCredits', wallet.free_crate_credits - case when uses_free_credit then 1 else 0 end,
    'outcome', outcome
  );
end;
$$;

revoke all on function public.open_crown_crate(uuid, uuid, integer, integer) from public, anon, authenticated;
grant execute on function public.open_crown_crate(uuid, uuid, integer, integer) to service_role;

commit;
