-- Crown Lizard global leaderboard. Run this once in the Supabase SQL editor.
create extension if not exists pgcrypto;

create table if not exists public.leaderboard_runs (
  id uuid primary key default gen_random_uuid(),
  difficulty text not null check (difficulty in ('chill', 'arcade', 'crowned')),
  game_version text not null check (game_version ~ '^\d+\.\d+\.\d+-\d+$'),
  ip_hash text not null check (char_length(ip_hash) = 64),
  created_at timestamptz not null default now(),
  used_at timestamptz
);

create table if not exists public.leaderboard_scores (
  id uuid primary key default gen_random_uuid(),
  run_id uuid not null unique references public.leaderboard_runs(id) on delete restrict,
  initials text not null check (initials ~ '^[A-Z0-9]{3}$'),
  score integer not null check (score between 1 and 1000000000),
  difficulty text not null check (difficulty in ('chill', 'arcade', 'crowned')),
  duration_ms integer not null check (duration_ms between 3000 and 86400000),
  zone integer not null check (zone between 1 and 999),
  wardens integer not null check (wardens between 0 and 999),
  enemies integer not null check (enemies between 0 and 1000000),
  crates integer not null check (crates between 0 and 100000),
  best_combo integer not null check (best_combo between 1 and 100000),
  game_version text not null check (game_version ~ '^\d+\.\d+\.\d+-\d+$'),
  is_hidden boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists leaderboard_runs_rate_limit_idx
  on public.leaderboard_runs (ip_hash, created_at desc);

create index if not exists leaderboard_scores_rank_idx
  on public.leaderboard_scores (difficulty, score desc, created_at asc);

alter table public.leaderboard_runs enable row level security;
alter table public.leaderboard_scores enable row level security;

-- No public policies are intentional. Only the encrypted Supabase secret held by
-- the Cloudflare Pages Function may read or write leaderboard data.

-- Server-authoritative player identity and Crown Vault state.
alter table public.leaderboard_runs
  add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.leaderboard_runs
  add column if not exists economy_settled_at timestamptz;

create table if not exists public.player_wallets (
  user_id uuid primary key references auth.users(id) on delete cascade,
  balance integer not null default 0 check (balance between 0 and 1000000000),
  opens integer not null default 0 check (opens between 0 and 1000000000),
  since_sovereign integer not null default 0 check (since_sovereign between 0 and 199),
  equipped_ship text not null default 'ship_default',
  legacy_imported_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.player_inventory (
  user_id uuid not null references auth.users(id) on delete cascade,
  cosmetic_id text not null,
  source text not null check (source in ('crate', 'shop', 'sponsored', 'grant', 'legacy')),
  acquired_at timestamptz not null default now(),
  primary key (user_id, cosmetic_id)
);

create table if not exists public.cosmetic_catalog (
  id text primary key,
  rarity text not null check (rarity in ('uncommon', 'rare', 'royal', 'mythic', 'sovereign')),
  sort_order integer not null,
  active boolean not null default true
);

insert into public.cosmetic_catalog (id, rarity, sort_order) values
  ('ship_verdant_scout', 'uncommon', 10),
  ('ship_ember_runner', 'uncommon', 20),
  ('ship_crystal_dart', 'uncommon', 30),
  ('ship_void_hunter', 'rare', 40),
  ('ship_solar_guard', 'rare', 50),
  ('ship_royal_vanguard', 'royal', 60),
  ('ship_rift_phantom', 'mythic', 70),
  ('ship_crown_sovereign', 'sovereign', 80)
on conflict (id) do update
  set rarity = excluded.rarity,
      sort_order = excluded.sort_order,
      active = true;

create table if not exists public.economy_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  external_id text not null,
  kind text not null,
  amount integer not null,
  balance_after integer not null check (balance_after between 0 and 1000000000),
  run_id uuid references public.leaderboard_runs(id) on delete restrict,
  opening_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (user_id, external_id)
);

create table if not exists public.auth_bootstrap_events (
  id bigint generated by default as identity primary key,
  ip_hash text not null check (char_length(ip_hash) = 64),
  created_at timestamptz not null default now()
);

create index if not exists player_inventory_user_idx
  on public.player_inventory (user_id, acquired_at);
create index if not exists economy_transactions_user_idx
  on public.economy_transactions (user_id, created_at desc);
create index if not exists auth_bootstrap_events_rate_idx
  on public.auth_bootstrap_events (ip_hash, created_at desc);

alter table public.player_wallets enable row level security;
alter table public.player_inventory enable row level security;
alter table public.cosmetic_catalog enable row level security;
alter table public.economy_transactions enable row level security;
alter table public.auth_bootstrap_events enable row level security;

revoke all on table public.player_wallets from anon, authenticated;
revoke all on table public.player_inventory from anon, authenticated;
revoke all on table public.cosmetic_catalog from anon, authenticated;
revoke all on table public.economy_transactions from anon, authenticated;
revoke all on table public.auth_bootstrap_events from anon, authenticated;

-- One-time legacy import. Only the server-side service role may execute it.
create or replace function public.import_legacy_wallet(
  p_user_id uuid,
  p_balance integer,
  p_opens integer,
  p_since_sovereign integer,
  p_equipped_ship text,
  p_cosmetic_ids text[]
) returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  imported boolean := false;
begin
  update public.player_wallets
     set balance = p_balance,
         opens = p_opens,
         since_sovereign = p_since_sovereign,
         equipped_ship = p_equipped_ship,
         legacy_imported_at = now(),
         updated_at = now()
   where user_id = p_user_id
     and legacy_imported_at is null
     and balance = 0
     and opens = 0;

  imported := found;
  if not imported then return false; end if;

  insert into public.player_inventory (user_id, cosmetic_id, source)
  select p_user_id, cosmetic_id, 'legacy'
    from unnest(p_cosmetic_ids) as cosmetic_id
  on conflict (user_id, cosmetic_id) do nothing;

  insert into public.economy_transactions (user_id, external_id, kind, amount, balance_after, metadata)
  values (p_user_id, 'legacy-import', 'legacy_import', p_balance, p_balance,
    jsonb_build_object('opens', p_opens, 'cosmetics', cardinality(p_cosmetic_ids)));
  return true;
end;
$$;

revoke all on function public.import_legacy_wallet(uuid, integer, integer, integer, text, text[]) from public, anon, authenticated;
grant execute on function public.import_legacy_wallet(uuid, integer, integer, integer, text, text[]) to service_role;

-- Atomically credits one verified server run exactly once.
create or replace function public.settle_run_reward(
  p_user_id uuid,
  p_run_id uuid,
  p_amount integer,
  p_reward jsonb
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  run_row public.leaderboard_runs%rowtype;
  wallet_balance integer;
  existing_tx public.economy_transactions%rowtype;
begin
  if p_amount < 0 or p_amount > 150 then
    raise exception 'invalid reward amount';
  end if;

  select * into run_row
    from public.leaderboard_runs
   where id = p_run_id
   for update;

  if not found then raise exception 'run not found'; end if;
  if run_row.user_id is distinct from p_user_id then raise exception 'run owner mismatch'; end if;

  select * into existing_tx
    from public.economy_transactions
   where user_id = p_user_id and external_id = 'run:' || p_run_id::text;

  if found then
    return jsonb_build_object(
      'duplicate', true,
      'balance', existing_tx.balance_after,
      'amount', existing_tx.amount,
      'reward', existing_tx.metadata
    );
  end if;

  if run_row.economy_settled_at is not null then raise exception 'run already settled'; end if;

  insert into public.player_wallets (user_id)
  values (p_user_id)
  on conflict (user_id) do nothing;

  update public.player_wallets
     set balance = balance + p_amount,
         updated_at = now()
   where user_id = p_user_id
   returning balance into wallet_balance;

  update public.leaderboard_runs
     set economy_settled_at = now()
   where id = p_run_id;

  insert into public.economy_transactions (user_id, external_id, kind, amount, balance_after, run_id, metadata)
  values (p_user_id, 'run:' || p_run_id::text, 'run_reward', p_amount, wallet_balance, p_run_id, p_reward);

  return jsonb_build_object(
    'duplicate', false,
    'balance', wallet_balance,
    'amount', p_amount,
    'reward', p_reward
  );
end;
$$;

revoke all on function public.settle_run_reward(uuid, uuid, integer, jsonb) from public, anon, authenticated;
grant execute on function public.settle_run_reward(uuid, uuid, integer, jsonb) to service_role;

-- Atomically opens one paid Crown Crate. Random rolls come only from the trusted
-- Cloudflare function; all balance, pity and duplicate decisions happen under lock.
create or replace function public.open_crown_crate(
  p_user_id uuid,
  p_opening_id uuid,
  p_tier_roll integer,
  p_cosmetic_roll integer
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  wallet public.player_wallets%rowtype;
  existing_tx public.economy_transactions%rowtype;
  selected_tier text;
  selected_cosmetic text;
  guaranteed boolean;
  is_duplicate boolean;
  salvage integer;
  candidate_count integer;
  opening_number integer;
  resulting_balance integer;
  outcome jsonb;
begin
  if p_tier_roll < 0 or p_tier_roll > 9999 then raise exception 'invalid tier roll'; end if;
  if p_cosmetic_roll < 0 or p_cosmetic_roll > 999999 then raise exception 'invalid cosmetic roll'; end if;

  insert into public.player_wallets (user_id)
  values (p_user_id)
  on conflict (user_id) do nothing;

  select * into wallet
    from public.player_wallets
   where user_id = p_user_id
   for update;

  select * into existing_tx
    from public.economy_transactions
   where user_id = p_user_id and external_id = 'crate:' || p_opening_id::text;

  if found then
    return jsonb_build_object(
      'duplicateRequest', true,
      'balance', existing_tx.balance_after,
      'outcome', existing_tx.metadata->'outcome'
    );
  end if;

  if wallet.balance < 150 then
    return jsonb_build_object('error', 'NOT_ENOUGH_SHARDS', 'balance', wallet.balance);
  end if;

  guaranteed := wallet.since_sovereign >= 199;
  selected_tier := case
    when guaranteed then 'sovereign'
    when p_tier_roll < 5800 then 'uncommon'
    when p_tier_roll < 8600 then 'rare'
    when p_tier_roll < 9600 then 'royal'
    when p_tier_roll < 9950 then 'mythic'
    else 'sovereign'
  end;

  select count(*) into candidate_count
    from public.cosmetic_catalog
   where rarity = selected_tier and active;
  if candidate_count = 0 then raise exception 'empty cosmetic tier'; end if;

  select id into selected_cosmetic
    from public.cosmetic_catalog
   where rarity = selected_tier and active
   order by sort_order
   offset (p_cosmetic_roll % candidate_count)
   limit 1;

  -- Preserve the published first-opening guarantee even after a legacy import.
  if wallet.opens = 0 and exists (
    select 1 from public.player_inventory
     where user_id = p_user_id and cosmetic_id = selected_cosmetic
  ) then
    select count(*) into candidate_count
      from public.cosmetic_catalog catalog
     where catalog.rarity = selected_tier and catalog.active
       and not exists (
         select 1 from public.player_inventory owned
          where owned.user_id = p_user_id and owned.cosmetic_id = catalog.id
       );

    if candidate_count > 0 then
      select catalog.id into selected_cosmetic
        from public.cosmetic_catalog catalog
       where catalog.rarity = selected_tier and catalog.active
         and not exists (
           select 1 from public.player_inventory owned
            where owned.user_id = p_user_id and owned.cosmetic_id = catalog.id
         )
       order by catalog.sort_order
       offset (p_cosmetic_roll % candidate_count)
       limit 1;
    else
      select count(*) into candidate_count
        from public.cosmetic_catalog catalog
       where catalog.active
         and not exists (
           select 1 from public.player_inventory owned
            where owned.user_id = p_user_id and owned.cosmetic_id = catalog.id
         );
      if candidate_count > 0 then
        select catalog.id into selected_cosmetic
          from public.cosmetic_catalog catalog
         where catalog.active
           and not exists (
             select 1 from public.player_inventory owned
              where owned.user_id = p_user_id and owned.cosmetic_id = catalog.id
           )
         order by catalog.sort_order
         offset (p_cosmetic_roll % candidate_count)
         limit 1;
        select rarity into selected_tier from public.cosmetic_catalog where id = selected_cosmetic;
      end if;
    end if;
  end if;

  select exists (
    select 1 from public.player_inventory
     where user_id = p_user_id and cosmetic_id = selected_cosmetic
  ) into is_duplicate;

  salvage := case selected_tier
    when 'uncommon' then 15
    when 'rare' then 35
    when 'royal' then 75
    when 'mythic' then 150
    when 'sovereign' then 300
    else 0
  end;
  if not is_duplicate then salvage := 0; end if;

  opening_number := wallet.opens + 1;
  resulting_balance := wallet.balance - 150 + salvage;

  if not is_duplicate then
    insert into public.player_inventory (user_id, cosmetic_id, source)
    values (p_user_id, selected_cosmetic, 'crate')
    on conflict (user_id, cosmetic_id) do nothing;
  end if;

  update public.player_wallets
     set balance = resulting_balance,
         opens = opening_number,
         since_sovereign = case when selected_tier = 'sovereign' then 0 else least(199, wallet.since_sovereign + 1) end,
         updated_at = now()
   where user_id = p_user_id;

  outcome := jsonb_build_object(
    'openingId', p_opening_id,
    'openingNumber', opening_number,
    'cosmeticId', selected_cosmetic,
    'tier', selected_tier,
    'duplicate', is_duplicate,
    'salvageValue', salvage,
    'guaranteedSovereign', guaranteed,
    'source', 'crate',
    'createdAt', now()
  );

  insert into public.economy_transactions (user_id, external_id, kind, amount, balance_after, opening_id, metadata)
  values (
    p_user_id,
    'crate:' || p_opening_id::text,
    'crate_open',
    -150 + salvage,
    resulting_balance,
    p_opening_id,
    jsonb_build_object('cost', 150, 'salvage', salvage, 'outcome', outcome)
  );

  return jsonb_build_object('duplicateRequest', false, 'balance', resulting_balance, 'outcome', outcome);
end;
$$;

revoke all on function public.open_crown_crate(uuid, uuid, integer, integer) from public, anon, authenticated;
grant execute on function public.open_crown_crate(uuid, uuid, integer, integer) to service_role;

create or replace function public.equip_player_ship(
  p_user_id uuid,
  p_cosmetic_id text
) returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.player_wallets (user_id)
  values (p_user_id)
  on conflict (user_id) do nothing;

  perform 1 from public.player_wallets
   where user_id = p_user_id
   for update;

  if p_cosmetic_id <> 'ship_default' and not exists (
    select 1
      from public.player_inventory inventory
      join public.cosmetic_catalog catalog on catalog.id = inventory.cosmetic_id and catalog.active
     where inventory.user_id = p_user_id
       and inventory.cosmetic_id = p_cosmetic_id
  ) then
    return false;
  end if;

  update public.player_wallets
     set equipped_ship = p_cosmetic_id,
         updated_at = now()
   where user_id = p_user_id;
  return true;
end;
$$;

revoke all on function public.equip_player_ship(uuid, text) from public, anon, authenticated;
grant execute on function public.equip_player_ship(uuid, text) to service_role;
