import { cp, mkdir, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const requestedPlatform = process.argv.find(argument => argument.startsWith('--platform='))?.split('=')[1] || 'crownlizard';
if (!['crownlizard', 'crazygames'].includes(requestedPlatform)) throw new Error(`Unknown platform: ${requestedPlatform}`);
const profile = JSON.parse(await readFile(resolve(root, `platforms/${requestedPlatform}.json`), 'utf8'));
if (profile.id !== requestedPlatform) throw new Error(`Platform profile mismatch: ${requestedPlatform}`);

const output = resolve(root, requestedPlatform === 'crownlizard' ? 'dist' : 'dist-crazygames');
const crownPaths = [
  'about', 'assets', 'audio', 'contact', 'how-to-play', 'privacy', 'src', 'terms', 'updates',
  '_headers', '_routes.json', 'ads.txt', 'index.html', 'manifest.webmanifest', 'release.json',
  'robots.txt', 'sitemap.xml', 'site.css', 'styles.css', 'sw.js',
];
const crazyGamesPaths = ['assets', 'audio', 'src', 'index.html', 'release.json', 'styles.css'];
const publicPaths = requestedPlatform === 'crownlizard' ? crownPaths : crazyGamesPaths;

await rm(output, { recursive: true, force: true });
await mkdir(output, { recursive: true });
for (const path of publicPaths) await cp(resolve(root, path), resolve(output, path), { recursive: true });

const platformSource = `// Generated by tools/build-site.mjs. Do not edit this bundle file.\nexport const PLATFORM_BUILD = Object.freeze(${JSON.stringify(profile, null, 2)});\n`;
await writeFile(resolve(output, 'src/platform-config.js'), platformSource);

if (requestedPlatform === 'crazygames') {
  const indexPath = resolve(output, 'index.html');
  const crownIndex = await readFile(indexPath, 'utf8');
  const crazyGamesIndex = crownIndex
    .replace(/\s*<meta name="google-adsense-account"[^>]*>/, '')
    .replace(/\s*<link rel="canonical"[^>]*>/, '')
    .replace(/\s*<link rel="manifest"[^>]*>/, '')
    .replace(/\s*<link rel="apple-touch-icon"[^>]*>/, '')
    .replace(/\s*<meta name="apple-mobile-web-app-[^>]*>/g, '')
    .replace(/\s*<meta property="og:[^>]*>/g, '')
    .replace(/\s*<meta name="twitter:[^>]*>/g, '')
    .replace(/\s*<script type="application\/ld\+json">[\s\S]*?<\/script>/, '')
    .replace('</head>', '  <script src="https://sdk.crazygames.com/crazygames-sdk-v3.js"></script>\n</head>');
  await writeFile(indexPath, crazyGamesIndex);
}

const release = JSON.parse(await readFile(resolve(root, 'release.json'), 'utf8'));
await writeFile(resolve(output, 'build-meta.json'), JSON.stringify({ build: release.build, release: release.release, platform: profile.id }, null, 2));

const measure = async directory => {
  let files = 0;
  let bytes = 0;
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = resolve(directory, entry.name);
    if (entry.isDirectory()) {
      const nested = await measure(path);
      files += nested.files;
      bytes += nested.bytes;
    } else {
      files += 1;
      bytes += (await stat(path)).size;
    }
  }
  return { files, bytes };
};
const bundle = await measure(output);
console.log(`Built ${profile.label} for Build ${release.build} in ${output.split(/[\\/]/).at(-1)}/ (${bundle.files} files, ${(bundle.bytes / 1_048_576).toFixed(2)} MiB).`);
